name: zkevm-chain
on:
  workflow_dispatch:
  repository_dispatch:
    types: [zkevm-chain]
  schedule:
    - cron: '*/5 * * 7 *'

jobs:
  main:
    timeout-minutes: 5
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}
      AWS_DEFAULT_REGION: eu-central-1
      IMAGE_ID: ami-06ce824c157700cd2
      KEY_NAME: devops
      SUBNET_ID: subnet-07ce3c81e409f4e14
      SECURITY_GROUP_ID: sg-03c0a0de6836d583d
      #REPO: privacy-scaling-explorations/zkevm-chain
      REPO: ntampakas/github-ops
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v2
      - run: ./run.sh
